-- MySQL Script generated by MySQL Workbench
-- Fri Nov  4 22:07:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema el_tiempo_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema el_tiempo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `el_tiempo_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `el_tiempo_db` ;

-- -----------------------------------------------------
-- Table `el_tiempo_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_tiempo_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_tiempo_db`.`editoriales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_tiempo_db`.`editoriales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_tiempo_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_tiempo_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `autor` VARCHAR(255) NOT NULL,
  `idioma` VARCHAR(255) NOT NULL,
  `tapa` VARCHAR(255) NOT NULL,
  `precio` INT NOT NULL,
  `descuento` INT NULL DEFAULT NULL,
  `stock` INT NOT NULL,
  `descripcion` VARCHAR(1000) NOT NULL,
  `modelo` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `categoriesId` INT NOT NULL,
  `editorialesId` INT NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoriesId` (`categoriesId` ASC) VISIBLE,
  INDEX `editorialesId` (`editorialesId` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`categoriesId`)
    REFERENCES `el_tiempo_db`.`categories` (`id`),
  CONSTRAINT `products_ibfk_2`
    FOREIGN KEY (`editorialesId`)
    REFERENCES `el_tiempo_db`.`editoriales` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_tiempo_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_tiempo_db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_tiempo_db`.`carritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_tiempo_db`.`carritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productsId` INT NOT NULL,
  `usuariosId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productsId` (`productsId` ASC) VISIBLE,
  INDEX `usuariosId` (`usuariosId` ASC) VISIBLE,
  CONSTRAINT `carritos_ibfk_1`
    FOREIGN KEY (`productsId`)
    REFERENCES `el_tiempo_db`.`products` (`id`),
  CONSTRAINT `carritos_ibfk_2`
    FOREIGN KEY (`usuariosId`)
    REFERENCES `el_tiempo_db`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_tiempo_db`.`historiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_tiempo_db`.`historiales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `autor` VARCHAR(255) NOT NULL,
  `idioma` VARCHAR(255) NOT NULL,
  `tapa` VARCHAR(255) NOT NULL,
  `precio` INT NOT NULL,
  `descuento` INT NULL DEFAULT NULL,
  `stock` INT NOT NULL,
  `descripcion` VARCHAR(1000) NOT NULL,
  `modelo` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `categoriesId` INT NOT NULL,
  `editorialesId` INT NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoriesId` (`categoriesId` ASC) VISIBLE,
  INDEX `editorialesId` (`editorialesId` ASC) VISIBLE,
  CONSTRAINT `historiales_ibfk_1`
    FOREIGN KEY (`categoriesId`)
    REFERENCES `el_tiempo_db`.`categories` (`id`),
  CONSTRAINT `historiales_ibfk_2`
    FOREIGN KEY (`editorialesId`)
    REFERENCES `el_tiempo_db`.`editoriales` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_tiempo_db`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_tiempo_db`.`imagenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `productsId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productsId` (`productsId` ASC) VISIBLE,
  CONSTRAINT `imagenes_ibfk_1`
    FOREIGN KEY (`productsId`)
    REFERENCES `el_tiempo_db`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_tiempo_db`.`imagenes_historiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_tiempo_db`.`imagenes_historiales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `historialesId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `historialesId` (`historialesId` ASC) VISIBLE,
  CONSTRAINT `imagenes_historiales_ibfk_1`
    FOREIGN KEY (`historialesId`)
    REFERENCES `el_tiempo_db`.`historiales` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_tiempo_db`.`ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_tiempo_db`.`ordenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productsId` INT NOT NULL,
  `usuariosId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productsId` (`productsId` ASC) VISIBLE,
  INDEX `usuariosId` (`usuariosId` ASC) VISIBLE,
  CONSTRAINT `ordenes_ibfk_1`
    FOREIGN KEY (`productsId`)
    REFERENCES `el_tiempo_db`.`products` (`id`),
  CONSTRAINT `ordenes_ibfk_2`
    FOREIGN KEY (`usuariosId`)
    REFERENCES `el_tiempo_db`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `el_tiempo_db`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `el_tiempo_db`.`sequelizemeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
